GET http://localhost:3000/api/user HTTP/1.1
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTcxM2Y5ODNmMjI1ZjEzMmM1YWU0MmQiLCJpYXQiOjE1ODQ0ODAxNzQsImV4cCI6MTU4NDQ4MDUzNH0.EuY2uWcuO8rBTkiCFV-_tELZirHAcJYV3lk9eoII46I; HttpOnly

{}

###

POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "name": "kuba",
    "email": "kuba@email.com",
}