GET http://localhost:3000/api/user HTTP/1.1
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTRmZGUwZTZiZTZlYzA5YjhlMTRmZjQiLCJpYXQiOjE1ODI4MDY0MjAsImV4cCI6MTU4MjgxMDAyMH0.B5wvtre2yxEzDtDCu1geA2pfj4ykOtFjuVKQyBsgpcc

{}

###

POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "email": "kuba@email.com",
    "firstName": "kuba",
    "lastName": "2"
}