GET http://localhost:3000/api/user HTTP/1.1
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTUwNGIwZjlmYTUwYjBiNDRjNDc0M2UiLCJpYXQiOjE1ODI5OTc5NTQsImV4cCI6MTU4MzAwMTU1NH0.jknn_x3Zz-BfAefFDoWd2zEplPnGUcuB3z5E8Fx9prs

{}

###

POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "email": "kuba@email.com",
    "firstName": "kuba",
    "lastName": "2"
}