GET http://localhost:3000/api/user HTTP/1.1
content-type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTUwNGIwZjlmYTUwYjBiNDRjNDc0M2UiLCJpYXQiOjE1ODIzOTczMjYsImV4cCI6MTU4MjQwMDkyNn0.pxURVj12-GsnXOIU7nie9QeQdxO3uwT78CmwYsJ81_E

{}

###

POST http://localhost:3000/api/user HTTP/1.1
content-type: application/json

{
    "email": "kuba@email.com",
    "firstName": "kuba",
    "lastName": "2"
}